//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class hero_duel
    {
        public int hero_id { get; set; }
        public int duel_id { get; set; }
        public Nullable<int> heroNum { get; set; }
    
        public virtual duel duel { get; set; }
        public virtual hero hero { get; set; }
    }
}
