//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class round
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public round()
        {
            this.duel = new HashSet<duel>();
        }
    
        public int id { get; set; }
        public int num { get; set; }
        public string p1style { get; set; }
        public string p1base { get; set; }
        public Nullable<int> p1hp { get; set; }
        public string p2style { get; set; }
        public string p2base { get; set; }
        public Nullable<int> p2hp { get; set; }
        public string result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<duel> duel { get; set; }
    }
}
