//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class winrateView
    {
        public string Name { get; set; }
        public Nullable<int> WinRate { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Draws { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Rounds { get; set; }
        public Nullable<int> avgRounds { get; set; }
    }
}
